spring:
  datasource:
    url: jdbc:mysql://localhost:3306/daily_rates?useSSL=false&serverTimezone=Asia/Taipei
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true